import { db } from "../config/firebase";
import { User } from "../models/User";

export class UserDao {
  private collection = db.collection('users');

  /**
   * Creates a new user document in Firestore.
   * Automatically sets `createdAt` and `updatedAt` timestamps.
   *
   * @param {User} user - User object to create
   * @returns {Promise<string>} Returns the autogenerated Firestore document ID
   *
   * @example
   * const id = await UserDao.create({ name: "John", email: "john@mail.com" });
   */
  async create(user: User): Promise<string> {
    user.createdAt = new Date();
    user.updatedAt = new Date();
    const docRef = await this.collection.add(user);
    return docRef.id;
  }

  /**
   * Retrieves a user by Firestore document ID.
   *
   * @param {string} id - Firestore document ID
   * @returns {Promise<User | null>} Returns user data or null if not found
   *
   * @example
   * const user = await UserDao.getById("abc123");
   */
  async getById(id: string): Promise<User | null> {
    const doc = await this.collection.doc(id).get();
    if (!doc.exists) return null;
    return { id: doc.id, ...(doc.data() as User) };
  }

  /**
   * Updates a user by ID with partial user fields.
   * Automatically sets the `updatedAt` timestamp.
   *
   * @param {string} id - Firestore document ID
   * @param {Partial<User>} user - Fields to update
   * @returns {Promise<boolean>} True if update succeeded, false otherwise
   *
   * @example
   * await UserDao.update("abc123", { name: "New Name" });
   */
  async update(id: string, user: Partial<User>): Promise<boolean> {
    user.updatedAt = new Date();
    try {
      await this.collection.doc(id).update(user);
      return true;
    } catch {
      return false;
    }
  }

  /**
   * Deletes a user by Firestore document ID.
   *
   * @param {string} id - Firestore document ID
   * @returns {Promise<boolean>} True if deletion succeeded, false otherwise
   *
   * @example
   * await UserDao.delete("abc123");
   */
  async delete(id: string): Promise<boolean> {
    try {
      await this.collection.doc(id).delete();
      return true;
    } catch {
      return false;
    }
  }

  /**
   * Retrieves all users in the `users` collection.
   *
   * @returns {Promise<User[]>} Array of User objects
   *
   * @example
   * const users = await UserDao.getAll();
   */
  async getAll(): Promise<User[]> {
    const snapshot = await this.collection.get();
    return snapshot.docs.map(doc => ({ id: doc.id, ...(doc.data() as User) }));
  }

  /**
   * Retrieves a user by email.
   * - Normalizes the email (trim + lowercase)
   * - Searches using Firestore 'where' filter
   * - Returns the first match if one exists
   *
   * @param {string} searchEmail - Email to search for
   * @returns {Promise<User | null>} User if found, otherwise null
   *
   * @example
   * const user = await UserDao.userByEmail("example@mail.com");
   */
  async userByEmail(searchEmail: string): Promise<User | null> {
    try {
      const normalizedEmail = searchEmail.trim().toLowerCase();
      const querySnapshot = await this.collection
        .where('email', '==', normalizedEmail)
        .limit(1)
        .get();

      if (querySnapshot.empty) {
        return null;
      }

      const doc = querySnapshot.docs[0];
      return { id: doc.id, ...(doc.data() as User) };

    } catch (error) {
      console.error('Error searching user by email:', error);
      return null;
    }
  }

}

export default new UserDao();
