import { Request, Response, NextFunction } from "express";
import admin from "firebase-admin";

/**
 * Middleware to authenticate requests using Firebase Authentication
 * Verifies the JWT token sent in the Authorization header and add the user data to the request
 * 
 * @param {Request} req - Express request object
 * @param {Response} res - Express response object
 * @param {NextFunction} next - Express next function to pass control to the next middleware
 * @returns {Promise<void>} Calls next() if authentication succeeds, or sends 401 response if it fails
 */
export const authenticateFirebase = async (req: Request, res: Response, next: NextFunction) => {
  // Extract the Authorization header from the request
  // Expected format: "Bearer <token>"
  const authHeader = req.headers.authorization;
  
  // Check if Authorization header is present
  if (!authHeader) {
    res.status(401).json({ message: "Missing Authorization header" });
    return;
  }

  // Extract the token from the "Bearer <token>" format
  // Split by space and take the second part (index 1)
  const token = authHeader.split(" ")[1];

  try {
    // Verify the Firebase JWT token using Firebase Admin SDK
    // This checks:
    // - Token signature is valid
    // - Token hasn't expired (1 hour default)
    // - Token was generated by Firebase
    const decoded = await admin.auth().verifyIdToken(token);
    
    // Add the decoded user data to the request object
    // decoded contains: uid, email, email_verified, name, picture, etc.
    (req as any).user = decoded;
    
    // Pass control to the next middleware/route handler
    next();
  } catch (err) {
    // Token verification failed - could be:
    // - Invalid signature
    // - Expired token
    // - Malformed token
    // - Token from different Firebase project
    res.status(401).json({ message: "Invalid or expired token" });
    return;
  }
};