// This interface describes how a meeting object looks in the database.
// Each field represents a piece of information stored about a meeting.

export interface InformationMeetings {

    /**
     * Optional ID automatically generated by the database.
     * Example: "HGS82bs91ks0"
     */
    id?: string;

    /**
     * Public meeting ID that the system generates using nanoid.
     * This is the code shown to the user, usually in groups like "abc-123-def".
     * It's used to identify the meeting in the app.
     */
    idMeeting: string;

    /**
     * Date when the meeting was created.
     * It is set automatically when the meeting is created.
     * Example: new Date()
     */
    createdAt: Date;

    /**
     * The user who created the meeting.
     * Could be something like an email, UID, or username depending on the app.
     */
    createdBy: string;

    /**
     * Date when the meeting was finished.
     * If the meeting is still active, this value is null.
     * Example: null  → still active
     *          new Date() → finished
     */
    finishedAt: Date | null;
}
